### ISSUE TITLE
Explorer Sync Issues

### ISSUE THREAD

**Issue by itmilosIOHK** [input-output-hk/cardano-explorer-app#415] opened 2021-07-22 18:41 UTC
Hi, 

We have an issue with explorer, please see this block is unavailable - 

https://explorer.cardano.org/en/no-search-results?query=a68126a40f22bdfbe0c5632f874a98dfee0be8a32a1f9d319144a70238030ee7

but when you look for the block on blockchair it is available, what could be the error? 
 
https://blockchair.com/cardano/transaction/a68126a40f22bdfbe0c5632f874a98dfee0be8a32a1f9d319144a70238030ee7

**Comment by rhyslbw** [comment] 2021-07-23 00:30
It will be resolved the update to `cardano-graphql@5.0.0`, which is being prepare in: https://github.com/input-output-hk/cardano-explorer-app/pull/414)

**Comment by rhyslbw** [comment] 2021-07-23 00:31
Dupe of #412

**Closed by rhyslbw** 2021-07-23 00:31 UTC
