### ISSUE TITLE
input values displayed in transaction detail next to outputs

### ISSUE THREAD

**Issue by Logic999** [input-output-hk/cardano-explorer-app#310] opened 2020-06-22 10:50 UTC
Priyank on telegram asked me to create the issue here. He said "this looks like an issue on cardano explorer graphql end...the UTXO seems to be alright, but the transaction details did not get captured correctly..."

transaction ID : 90187ad0b966f3550c4d2e2d155dc5f389540a93a6043bdc0719ec7c7a4e1e7c

To DdzFFzCqrhsu1uKFD4R9zHvdwziXKYVgYWiVfK9XRPoSWRJ1peUByaGPY8VnNmGd8RfVyS6tKMBve8o2yPYZHbnfgiCqGm8tMhDR2Knd

Is showing different amounts on:
https://seiza.com/blockchain/transaction/90187ad0b966f3550c4d2e2d155dc5f389540a93a6043bdc0719ec7c7a4e1e7c

and 

https://explorer.cardano.org/en/transaction/?id=90187ad0b966f3550c4d2e2d155dc5f389540a93a6043bdc0719ec7c7a4e1e7c

19577.651648 on cardano explorer and 27565.686037 on seiza

**Comment by rhyslbw** [comment] 2020-06-22 11:55
Thanks @Logic999. Duplicate of https://github.com/input-output-hk/cardano-explorer-app/issues/304. I'll raise the priority on this internally, as it's clearly a sticking point.

**Comment by rdlrt** [comment] 2020-06-22 22:07
Hey @rhyslbw 
Can we keep the issue open until fixed?
Its easier to let people be pointed to (outside IOHK world) when hitting this issue - so that they know its known and being worked upon, instead of internal tracker which community has no visibility on :)

**Comment by DominikGuzei** [comment] 2020-06-29 12:46
This issue was fixed by #304

**Closed by DominikGuzei** 2020-06-29 12:46 UTC

**Comment by rhyslbw** [comment] 2020-07-08 15:19
Deployed to the [mainnet instance](https://explorer.cardano.org/)
