### ISSUE TITLE
Improve ux of latest epoch block list

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer-app#216] opened 2020-02-27 09:52 UTC
Navigate to the latest epoch and observe the behaviour of blocks being added.

- The list should not be changing size, with block rows added to the screen.
- The spinner should not be shown while fetching

**Comment by DominikGuzei** [comment] 2020-03-03 10:25
@rhyslbw with our `offset` and `limit` query logic this is the expected behavior (the latest page is always partially filled till the "limit" and then the next page is started with just the first record.

**Comment by rhyslbw** [comment] 2020-03-03 13:31
Ok, this is then blocked by https://github.com/input-output-hk/cardano-explorer-app/issues/192.

**Comment by DominikGuzei** [comment] 2020-03-04 19:32
@rhyslbw i will fix this issue, i just need to change the display logic so that the first page is the only one which is partially filled (basically switch around the logic).

**Comment by DominikGuzei** [comment] 2020-03-05 09:15
@rhyslbw ok so i tested the UX you described … the problem is that it doesn't work nicely with paging. If i write the query logic in a way that the last page is always trailing the latest 10 blocks (so that there are never fewer results as you mentioned) then all other "pages" are also dynamically adjusted and this feels weird because if you are at a page from "the past" it shouldn't change.

**Comment by a-rukin** [comment] 2020-03-10 09:08
Hmm...
Last page (ex **N** of **N**) should have remaining items from the list. So page **1** has **X**, page **2** has **X**, page **N** has "**total - total \ X**". 
Last page will eventually hit the **X**, and next step is that total amount of pages is increased, so we are on a page "**N** of **N+1**"

**Comment by DominikGuzei** [comment] 2020-03-12 16:11
@a-rukin ok then the "last page" will be special and there will be an overlap between last and second-last page (total - X) most of the time. We will need to add some logic to change the query params and everything when the next "last" page is created 👍

**Comment by a-rukin** [comment] 2020-03-16 10:33
> the "last page" will be special and there will be an overlap between last and second-last page (total - X) most of the time
@DominikGuzei I'm not sure I've understood you 
Let me try to explain one more time how I see it:
Imagine notebook with pages, each page has 20 rows
It's exactly the same what we should have here in our app/site
So you start filling your notebook row by row -> In some moment of time you have page which has current last row. This page could be incomplete and it's perfectly fine. 
Do we have any issues with this?

**Comment by DominikGuzei** [comment] 2020-03-16 12:12
that's exactly how it was before this PR 😅 i never had a problem with that, but Rhys created this issue, so i looked into it. If the UX you describe is fine we can savely ignore my PR and move on 👍

**Comment by DominikGuzei** [comment] 2020-03-18 17:37
@rhyslbw let's close this issue as the UX itself is resolved - the epoch performance issue is covered by #192

**Closed by DominikGuzei** 2020-03-18 17:37 UTC
Labels: bug
