### ISSUE TITLE
Byron Explorer. Search/Epoch navigation stalled.

### ISSUE THREAD

**Issue by DmitriiGaico** [input-output-hk/cardano-explorer-app#252] opened 2020-03-18 10:41 UTC
Sometimes Search or Navigating to Epoch cause Forever Loading with errors in Console.

![image](https://user-images.githubusercontent.com/45355947/76952427-c0513a80-6915-11ea-9eb0-26dfdf19769d.png)

**Comment by DominikGuzei** [comment] 2020-03-19 21:05
@DmitriiGaico i cannot reproduce this issue on latest develop, can you re-check?

**Comment by DeeJayElly** [comment] 2020-03-20 19:24
> @DmitriiGaico i cannot reproduce this issue on latest develop, can you re-check?

@DmitriiGaico @DominikGuzei same, i tried multiple stuff and now luck

**Comment by DeeJayElly** [comment] 2020-03-20 21:46
@DmitriiGaico @DominikGuzei managed to reproduce it and found the issue.

Its fixed now.

**Closed** 2020-03-23 14:18 UTC
Labels: bug
