### ISSUE TITLE
Cardano explorer -> not showing key deposit refunds

### ISSUE THREAD

**Issue by ntfreem** [input-output-hk/cardano-explorer-app#354] opened 2020-09-03 11:38 UTC
**Summary**

The Cardano explorer does not show refunds, in particular, when you deregister a stake key or stake pool, the deposit for that registration is refunded. So upon initial analysis of inputs and outputs, some transactions look unbalanced.

**Steps to reproduce**

De-register a stake pool key and check the cardano-explorer

**Expected results**

All key deposit refunds received from staking should be seen and included in the UTXO distribution and marked accordingly, a field representing in the transaction structure, something to verify that it’s a legal transaction.

**Actual results**
At the moment there is no indication of any refund transaction or otherwise. Instead, we only see a balance increase.

**Conclusion**

The explorer should also report refunds.

**Comment by rhyslbw** [comment] 2020-09-17 15:02
Duplicate of #353

**Closed by rhyslbw** 2020-09-17 15:02 UTC
